language: node_js
addons:
  sonarcloud:
    organization: loopingz-github
node_js:
- '8'
script:
- npm run test
after_success:
- sonar-scanner
before_deploy:
- npm run build
deploy:
  provider: npm
  email: rcattiau@loopingz.com
  skip_cleanup: true
  tag: next
  on:
    tags: true
  api_key:
    secure: NRsN3Bk4DVq/J2VSaPdHKTdXHhXJo6oApch42IH6uJ3xtXyx6ez4EiFEw8aiQTTW52eZR0amVLmSdWnH80J4kREbCIiBbSDiFYzIUgMDTiF2jvTT6TMmu4CwTNdYtNNhkGkjPus89tZQ/rvDFg3AdaTRaWWPP8iCqukWf5R1bnrY1ZMFHKrjgQ1Vv4qFkm3nESwj9mJbw48JTYZiefRcOvqCzNYcZMfxTQ8FEVhxnFxte+Yw2hPAJ8WmcvKi67BkAQkgmkCg9zmSzZWZjdiM0jEO/RQCnz+F7r/lJ4u0szasEADGSc4J8MaBDZNEv8Bvu175cD2AQ6GNnwHDDASEvpLOACX+fHU71hFV1a3T/IMfvzYq0OWIUswdpmSjs3Hf5yd1XS7ToFqXnBeBHKQp3uBtd2RXXC/UEX6jMVhSwqt8ZZekmjbhH+eap/T/xBqqy1XDOiVUYtUYIzPN4cMCT+tU7w9vPasxCRvKqPEA/AyWAspqxhWr8GIyrSaOlkvVYZauqREOJqnQpdPq0Y7MscgMPq0MeEbXKDTrY9+0D6KCJhy6xAjkQw6MBaZqKFHe46G+VbwD17E+008aDU4XtlVKm2/JTJOjF7rY7y2hIjH627qq8hKVE7RoHobIoO3Csr8DcbUduqoHb/YADHLj3W96cjupMLTrtFZd4IKQtro=
